stages:
  - build_1
  - build_2
  - build_3
  
build_cms_grid:
  stage: build_1
  tags:
    - docker-image-build
  script:
    - docker build -t cms_grid .
  variables:
    TO: $CI_REGISTRY_IMAGE:cms_grid # where to push resulting image
    CONTEXT_DIR: cms_grid
    FROM: cern/slc6-base:latest


build_jenkins_python:
  stage: build_1
  tags:
    - docker-image-build
  script:
    - docker build -t jenkins_python .
  variables:
    TO: $CI_REGISTRY_IMAGE:jenkins_python # where to push resulting image
    CONTEXT_DIR: jenkins_python
    FROM: python:2

build_wmcore_base:
  stage: build_2
  tags:
    - docker-image-build
  script:
    - docker build -t wmcore_base .
  variables:
    TO: $CI_REGISTRY_IMAGE:wmcore_base # where to push resulting image
    CONTEXT_DIR: wmcore_base
    FROM: $CI_REGISTRY_IMAGE:cms_grid

build_wmcore_tests:
  stage: build_3
  tags:
    - docker-image-build
  script:
    - docker build -t wmcore_tests .
  variables:
    TO: $CI_REGISTRY_IMAGE:wmcore_tests # where to push resulting image
    CONTEXT_DIR: wmcore_tests
    FROM: $CI_REGISTRY_IMAGE:wmcore_base

build_dbs_tests:
  stage: build_3
  tags:
    - docker-image-build
  script:
    - docker build -t dbs_tests .
  variables:
    TO: $CI_REGISTRY_IMAGE:dbs_tests # where to push resulting image
    CONTEXT_DIR: dbs_tests
    FROM: $CI_REGISTRY_IMAGE:wmcore_base

build_crab_tests:
  stage: build_3
  tags:
    - docker-image-build
  script:
    - docker build -t crab_tests .
  variables:
    TO: $CI_REGISTRY_IMAGE:crab_tests # where to push resulting image
    CONTEXT_DIR: crab_tests
    FROM: $CI_REGISTRY_IMAGE:wmcore_base


